# Generated by Django 5.1.4 on 2025-07-17 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='num_like',
            field=models.IntegerField(default=0),
        ),
    ]
