# Generated by Django 5.2.4 on 2025-07-17 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_task_num_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='priority',
            field=models.IntegerField(choices=[(1, 'Low'), (2, 'Middle'), (3, 'High')], default=2),
        ),
    ]
